# Generated by Django 5.2.17 on 2026-09-12 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consorcios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consorcio',
            name='administrador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consorcios_administrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='unidad',
            name='consorcio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='consorcios.consorcio'),
        ),
        migrations.AddField(
            model_name='unidad',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='unidad',
            unique_together={('consorcio', 'numero')},
        ),
    ]
